"""Initial Migration

Revision ID: 4f5bd8c88934
Revises: 77195b4a0c72
Create Date: 2019-03-04 08:46:16.093024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5bd8c88934'
down_revision = '77195b4a0c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscribes_blog_id_fkey', 'subscribes', type_='foreignkey')
    op.drop_column('subscribes', 'blog_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscribes_blog_id_fkey', 'subscribes', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###
