"""Initial Migration

Revision ID: d12fa71b496f
Revises: e80f8cee31c1
Create Date: 2019-03-02 12:55:13.521894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12fa71b496f'
down_revision = 'e80f8cee31c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'username')
    # ### end Alembic commands ###
